---
-
  become: true
  hosts: all
  become_method: sudo
  become_user: root
  tasks:
  - name: Disabled AutoUpdate
    copy:
      dest: "/etc/apt/apt.conf.d/20auto-upgrades"
      content: |
        APT::Periodic::Update-Package-Lists "0";
        APT::Periodic::Unattended-Upgrade "0";

  - name: Unconditionally reboot the machine with all defaults
    ansible.builtin.reboot:
