---
-
  become: true
  hosts: all
  become_method: sudo
  become_user: root
  tasks:
  - name: Install Docker
    shell: curl -sSL https://get.docker.com/ | sh

  - name: Creating /etc/docker/daemon.json
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
         "exec-opts": ["native.cgroupdriver=systemd"],  
         "log-driver": "json-file",
         "log-opts": {
           "max-size": "100m"
         },
         "storage-driver": "overlay2"
        }  

  - name: Restart Docker
    service:
      name: "docker"
      state: "restarted"
      enabled: "yes"

  # View the name of the correct version: curl -s https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-amd64/Packages | grep Version | awk '{print $2}'

  - name: Install-Kubernetes 1.23.17-00
    shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list && sudo apt-get update -q && sudo apt-get install -qy kubelet=1.23.17-00 kubectl=1.23.17-00 kubeadm=1.23.17-00

#  - name: Install-Kubernetes 1.19.16-00
#    shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list && sudo apt-get update -q && sudo apt-get install -qy kubelet=1.19.16-00 kubectl=1.19.16-00 kubeadm=1.19.16-00

  - name: Disabled update kubelet kubeadm kubectl
    shell: apt-mark hold kubelet kubeadm kubectl
    
