---
-
  become: true
  hosts: masters,worknodes
  become_method: sudo
  become_user: root
  tasks:
  - name: Update APT
    apt:
      update_cache: yes

  - name: Install packeges
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - wget
        - git
        - htop
        - net-tools
        - mc
        - screen
        